<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageType>Template</PackageType>
    <PackageVersion>1.0.20</PackageVersion>
    <PackageId>MinimalApi.Template</PackageId>
    <Title>Minimal Api Template</Title>
    <Authors>Angelo Pirola</Authors>
    <Description>A .NET Web Minimal API Template for quickly starting new projects.</Description>
    <PackageTags>dotnet-new;templates;minimalapi;dotnet;webapi</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/AngeloDotNet/MinimalApi.Template</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/AngeloDotNet/MinimalApi.Template</RepositoryUrl>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="content\**\*" Exclude="content\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>