<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
		<!--<PackageReference Include="ISM.Database.SQLServer" Version="1.0.6" />-->
		<PackageReference Include="TinyAppEngine" Version="1.0.28" />
		<PackageReference Include="TinyAppEngine.Tools" Version="1.0.46" />
	</ItemGroup>

</Project>
