global using AppEngine.Logging;
global using AppEngine.Routing;
global using AppEngine.Tools;
global using AppEngine.Tools.DependencyInjection;
global using AppEngine.Tools.Enums;
global using AppEngine.Tools.Extensions;
global using AppEngine.Tools.OperationResults;
global using AppEngine.Tools.OperationResults.AspNetCore.Http;
global using AppEngine.Tools.Settings;
global using AppEngine.Tools.TimeZoneService;
global using AppEngine.Tools.TimeZoneService.Interfaces;
global using AppEngine.Validations.Validation;
global using AppEngine.Versioning.Options;
global using EntityFramework.Exceptions.SqlServer;
global using FluentValidation;
global using Microsoft.AspNetCore.HttpOverrides;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Caching.Distributed;
global using Microsoft.Net.Http.Headers;
global using Microsoft.OpenApi;
global using MinimalApi.Template.Api.Endpoints;
global using MinimalApi.Template.Api.Extensions;
global using MinimalApi.Template.BusinessLayer;
global using MinimalApi.Template.BusinessLayer.Context;
global using MinimalApi.Template.DataAccessLayer;
global using Scalar.AspNetCore;
global using Serilog;
global using Serilog.Core;
global using System.Text;
global using System.Text.Json;
global using ErrorResponseFormat = AppEngine.Validations.Validation.ErrorResponseFormat;
global using ErrorResposeFormatOR = AppEngine.Tools.OperationResults.AspNetCore.Http.ErrorResponseFormat;
global using ServiceCollectionExtensions = AppEngine.Tools.DependencyInjection.ServiceCollectionExtensions;