<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Angelo Pirola</Authors>
    <Company>Angelo Pirola</Company>
    <Product>NETWebApiTemplate</Product>
    <Title>NET Web Minimal API Template</Title>
    <Description>A .NET Web Minimal API Template for quickly starting new projects.</Description>
    <PackageId>NETWebApi.Template</PackageId>
    <PackageType>Template</PackageType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/AngeloDotNet/MyWebApiTemplate</PackageProjectUrl>
    <PackageTags>dotnet;csharp;template;webapi;minimalapi;</PackageTags>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/AngeloDotNet/MyWebApiTemplate.git</RepositoryUrl>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>src</ContentTargetFolders>
    <RepositoryBranch>main</RepositoryBranch>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Exceptions.SqlServer" Version="10.0.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    <PackageReference Include="TinyAppEngine" Version="1.0.28" />
    <PackageReference Include="TinyAppEngine.Tools" Version="1.0.41" />
  </ItemGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>
</Project>