name: publish

on:
  push:
    branches: [ main ]

env:
  NET_VERSION: '10.x'
  PROJECT_FILENAME: MinimalApi.Template.csproj

jobs:
  build:
    name: Publish on NuGet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET SDK ${{ env.NET_VERSION }}
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.NET_VERSION }}
        dotnet-quality: 'ga'
    
    - name: Package
      run: dotnet pack -c Release -o . ./${{ env.PROJECT_FILENAME }}
    
    - name: Publish on NuGet
      run: dotnet nuget push *.nupkg -k ${{ secrets.BAGET_API_KEY }} -s ${{ secrets.BAGET_HOST }} --allow-insecure-connections
